services:
  app-ci:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: ci
    working_dir: /work
    volumes:
      - ./:/work:cached
      - pip-cache:/tmp/pip-cache
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /work/src
      RUFF_CACHE_DIR: /tmp/.ruff_cache
      PYTEST_CACHE_DIR: /tmp/.pytest_cache
    command: make ci-light
    tty: false

volumes:
  pip-cache: