name: photo_eval_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=25.0.1          # ★ バージョン明示
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.6.2
  - pillow=8.4.0
  - pyyaml=6.0
  - scikit-learn=1.0.2
  - scipy=1.9.3
  - seaborn=0.11.2
  - tqdm=4.64.1
  - opencv
