name: eval-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.23.5
  - scipy=1.9.3
  - pandas=1.5.3
  - matplotlib=3.6.2
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - tqdm=4.64.1
  - pillow=8.4.0
  - opencv=4.5.3
  - yaml
  - pip
  - pip:
      # PyTorch with CUDA 12.7
      - torch==2.2.0+cu127
      - torchvision==0.17.0+cu127
      - torchaudio==2.2.0+cu127
      - --extra-index-url https://download.pytorch.org/whl/cu127

      # 顔検出と整列
      - insightface==2.0.0
      - retina-face==0.0.1
      - face-alignment==1.3.4
      - dlib==19.24.1

      # 全身検出と構図評価
      - mediapipe==0.8.11
      - detecto==1.6.1

      # 画像処理と拡張
      - scikit-image==0.19.3
      - albumentations==1.3.0
      - albumentations-pytorch==0.1.0
      - imgaug==0.4.0

      # 評価指標
      - torchmetrics==0.11.2

      # 実験追跡と設定
      - wandb==0.15.0
      - pyyaml==6.0

      # ログ強化
      - loguru==0.7.2
      - coloredlogs==15.0.1
      - python-json-logger==2.0.7
      - rich==13.7.0
