# config.yaml

# EXIFデータに含めるフィールドのリスト
exif_fields:
  - "FileName"
  - "Model"
  - "Lens"
  - "ExposureTime"
  - "FocalLength"
  - "ShutterSpeed"
  - "Aperture"
  - "ISO"
  - "Rating"
  - "ImageHeight"
  - "ImageWidth"
  - "Orientation"
  - "BitDepth"

# 出力先ディレクトリ（デフォルト: temp）
output_directory: "temp"
paths:
  thresholds_file: "./config/thresholds.yaml"
  evaluation_data_dir: "./temp"
  output_data_dir: "./output"

# EXIFデータをCSVファイルに追加するモード（True で追加、False で上書き）
append_mode: false

# 基本のディレクトリパス（例: /mnt/l/picture/2024/2024-08-26）
base_directory: "/mnt/l/picture/2024/"
base_directory_root: "/mnt/l/picture/2024/"

# ターゲット日付
target_date: "2024-05-01"

defaults:
  min_score: 0.0
  max_score: 1.0

weights:
  face_detected:
    face_sharpness: 0.4
    face_contrast: 0.1
    overall_sharpness: 0.3
    overall_contrast: 0.1
    overall_blurriness: 0.1
  no_face_detected:
    overall_sharpness: 0.6
    overall_contrast: 0.2
    overall_blurriness: 0.2
