# config.yaml

# EXIFデータに含めるフィールドのリスト
exif_fields:
  - "FileName"
  - "Model"
  - "Lens"
  - "ExposureTime"
  - "FocalLength"
  - "ShutterSpeed"
  - "Aperture"
  - "ISO"
  - "Rating"
  - "ImageHeight"
  - "ImageWidth"
  - "Orientation"
  - "BitDepth"

# 出力先ディレクトリ（デフォルト: temp）
output_directory: "temp"
paths:
  thresholds_file: "./config/thresholds.yaml"
  evaluation_data_dir: "./temp"
  output_data_dir: "./output"

# EXIFデータをCSVファイルに追加するモード（True で追加、False で上書き）
append_mode: false

# 基本のディレクトリパス（例: /mnt/l/picture/2024/2024-08-26）
base_directory: "/mnt/l/picture/2025/"
base_directory_root: "/mnt/l/picture/2025/"

# ターゲット日付
target_date: "2025-01-01"

defaults:
  min_score: 0.0
  max_score: 1.0

weights:
  face_detected:
    face_sharpness_score: 0.3
    face_contrast_score: 0.2
    face_noise_score: 0.1
    sharpness_score: 0.2
    contrast_score: 0.1
    noise_score: 0.1
    blurriness_score: 0.0
  no_face_detected:
    sharpness_score: 0.5
    contrast_score: 0.3
    noise_score: 0.2
    blurriness_score: 0.0

batch_size: 10

batch:
  memory_threshold: 90  # デフォルト値。使用率が90%以上になったら停止

debug:
  log_summary_detail: true