version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  simple:
    format: '%(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    when: midnight
    backupCount: 7
    encoding: utf8

  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    when: midnight
    backupCount: 7
    encoding: utf8

loggers:
  MyAppLogger:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no
