name: Run Pytest

on:
  push:
    branches:
      - main  # mainブランチにpushしたときにCIを実行
  pull_request:
    branches:
      - main  # mainブランチにPRを作成したときにCIを実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: 4.12.0
        python-version: 3.10  # 必要に応じてPythonのバージョンを変更
        environment-file: environment_combined.yml

    - name: Install dependencies
      run: |
        conda env update --file environment_combined.yml --prune  # 必要なパッケージをインストール
        conda activate photo_eval_env  # 仮想環境をアクティブ化
        pip install -r pip_requirements.txt  # pipの依存関係もインストール

    - name: Run tests
      run: |
        pytest  # テストを実行
